version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    cooldown:
      default-days: 7
    labels:
      - 'go'
      - 'dependencies'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      day: saturday
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - 'actions/*'
      docker:
        patterns:
          - 'docker/*'
    labels:
      - 'dependencies'
      - 'github-actions'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      day: saturday
      interval: 'weekly'
    cooldown:
      default-days: 7
    labels:
      - 'docker'
      - 'dependencies'
