---
name: migration

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

concurrency:
  group: migration

permissions: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        type:
          - theme
          - plugin
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: registry login
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 #v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: pull image
        run: docker pull ghcr.io/trywpm/wp-to-wpm:latest

      - name: run migration
        run: |
          docker run --rm \
            -e WORKERS=2 \
            -e WPM_TOKEN=${{ secrets.WPM_TOKEN }} \
            -e PACKAGE_TYPE=${{ matrix.type }} \
            -v ${{ github.workspace }}:/code \
            ghcr.io/trywpm/wp-to-wpm:latest migrate
        env:
          WORKERS: 2

      - name: set user
        run: |
          git config --global user.name "thelovekeshbot"
          git config --global user.email "bots@thelovekesh.com"

      - name: commit changes
        run: |
          git pull origin main
          git add .${{ matrix.type }}_last_rev
          git commit -m "Update .${{ matrix.type }}_last_rev" || echo "No changes to commit"

      - name: push changes
        run: |
          git pull --rebase origin main || true
          git push origin main
