---
name: migration

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

concurrency:
  group: migration

permissions: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        type:
          - theme
          - plugin
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          lfs: true

      - name: setup wpm
        working-directory: /tmp
        run: |
          wget https://github.com/trywpm/cli/releases/latest/download/wpm-linux-amd64
          wget https://github.com/trywpm/cli/releases/latest/download/wpm-linux-amd64.sha256
          sha256sum -c wpm-linux-amd64.sha256
          chmod +x wpm-linux-amd64
          sudo mv wpm-linux-amd64 /usr/local/bin/wpm

      - name: setup svn
        run: sudo apt install -y subversion

      - name: wpm login
        run: |
          wpm auth login --token ${{ secrets.WPM_TOKEN }}

      - name: run migration
        run: ./bin/migrate --type ${{ matrix.type }} --workers 2

      - name: set user
        run: |
          git config --global user.name "thelovekeshbot"
          git config --global user.email "bots@thelovekesh.com"

      - name: commit changes
        run: |
          git add .${{ matrix.type }}_last_rev
          git commit -m "Update .${{ matrix.type }}_last_rev" || echo "No changes to commit"

      - name: push changes
        run: git push origin main
